apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis-allow-authorized
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: redis-db
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: resume-api
    - podSelector:
        matchLabels:
          role: redis-backup
    ports:
    - protocol: TCP
      port: 6379
    - protocol: TCP
      port: 4143   # Linkerd mTLS port
    - protocol: TCP
      port: 4191   # Linkerd health check port
