apiVersion: v1
kind: ServiceAccount
metadata:
  name: resume-api-sa
  namespace: default
---
apiVersion: policy.linkerd.io/v1alpha1
kind: MeshTLSAuthentication
metadata:
  name: api-auth-mtls
  namespace: default
spec:
  identities:
    - "resume-api-sa.default.serviceaccount.cluster.local"
