apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - services.yaml
  - redis-deployment.yaml
  - api-deployment.yaml
  - redis-policy.yaml
  - tunnel-connector.yaml
  - api-auth.yaml
