apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-auth.yaml
  - api-deployment.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - redis-deployment.yaml
  - redis-policy.yaml
  - tunnel-connector.yaml

configMapGenerator:
- name: resume-content
  files:
    - index.html=index.html
