apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: resume-service
  spec:
    type: LoadBalancer
    selector:
      app: resume-api
    ports:
    - name: cloudflare-port
      port: 8081
      targetPort: 5000
      protocol: TCP

- apiVersion: v1
  kind: Service
  metadata:
    name: resume-frontend-service
  spec:
    type: LoadBalancer
    selector:
      app: resume  # <--- FIXED: Now points to Nginx pods
    ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP

- apiVersion: v1
  kind: Service
  metadata:
    name: redis-db
  spec:
    type: ClusterIP
    selector:
      app: redis-db
    ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
